[project]
name = "integrated-api"
authors = ["Alice Johnson <alice@example.com>"]
description = "Decentralized Health Data Management Platform"
telemetry = false
requirements = []
[contracts.health-api]
path = "contracts/health-api.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
